export type FormulaStudentCompetition = {
  name: string;
  country: string;
  venue: string;
  worldRanking: boolean;
  dateLabel: string;
  dateConfirmed: boolean;
  startDate?: string;
  endDate?: string;
  sourceUrl: string;
};

// FSG'nin aktif yarışmalar dizini ve organizatörlerin kendi sayfaları
// 9 Eylül 2026 tarihinde kontrol edildi. Açıklanmamış 2027 tarihleri,
// önceki yılın tarihi ileri taşınmadan özellikle beklemede bırakıldı.
export const formulaStudentCompetitions2027: FormulaStudentCompetition[] = [
  {
    name: 'Formula Student Germany',
    country: 'Almanya',
    venue: 'Hockenheim',
    worldRanking: true,
    dateLabel: '10–15 Ağustos 2027',
    dateConfirmed: true,
    startDate: '2027-08-10',
    endDate: '2027-08-15',
    sourceUrl: 'https://www.formulastudent.de/',
  },
  {
    name: 'Formula Student Austria',
    country: 'Avusturya',
    venue: 'Spielberg',
    worldRanking: true,
    dateLabel: '2027 tarihi bekleniyor',
    dateConfirmed: false,
    sourceUrl: 'https://fsaustria.at/',
  },
  {
    name: 'Formula Student Alpe Adria',
    country: 'Hırvatistan',
    venue: 'Mičevec / Velika Gorica',
    worldRanking: true,
    dateLabel: '2027 tarihi bekleniyor',
    dateConfirmed: false,
    sourceUrl: 'https://fs-alpeadria.com/',
  },
  {
    name: 'Formula Student Czech Republic',
    country: 'Çekya',
    venue: 'Most',
    worldRanking: true,
    dateLabel: '2027 sezonu duyuruldu; tarih bekleniyor',
    dateConfirmed: false,
    sourceUrl: 'https://fsczech.cz/',
  },
  {
    name: 'Formula Student France',
    country: 'Fransa',
    venue: 'Saint-Maurice-de-Rémens',
    worldRanking: true,
    dateLabel: '2027 tarihi bekleniyor',
    dateConfirmed: false,
    sourceUrl: 'https://fs-france.com/',
  },
  {
    name: 'Formula Student East',
    country: 'Macaristan',
    venue: 'Zalaegerszeg',
    worldRanking: true,
    dateLabel: '2027 tarihi bekleniyor',
    dateConfirmed: false,
    sourceUrl: 'https://fseast.eu/',
  },
  {
    name: 'Formula SAE Italy',
    country: 'İtalya',
    venue: "Varano de' Melegari",
    worldRanking: true,
    dateLabel: '2027 organizasyonu doğrulandı; tarih bekleniyor',
    dateConfirmed: false,
    sourceUrl: 'https://www.formula-ata.it/',
  },
  {
    name: 'Formula Student Poland',
    country: 'Polonya',
    venue: 'Poznań',
    worldRanking: true,
    dateLabel: '2027 tarihi bekleniyor',
    dateConfirmed: false,
    sourceUrl: 'https://fs-poland.pl/',
  },
  {
    name: 'Formula Student Portugal',
    country: 'Portekiz',
    venue: 'Castelo Branco / Lisboa',
    worldRanking: true,
    dateLabel: '2027 tarihi bekleniyor',
    dateConfirmed: false,
    sourceUrl: 'https://www.formulastudent.pt/',
  },
  {
    name: 'Formula Student Spain',
    country: 'İspanya',
    venue: 'Barcelona',
    worldRanking: true,
    dateLabel: '2027 tarihi bekleniyor',
    dateConfirmed: false,
    sourceUrl: 'https://www.formulastudent.es/',
  },
  {
    name: 'Formula Student Switzerland',
    country: 'İsviçre',
    venue: 'Geschinen',
    worldRanking: true,
    dateLabel: '2027 tarihi bekleniyor',
    dateConfirmed: false,
    sourceUrl: 'https://www.fsswitzerland.ch/',
  },
  {
    name: 'Formula Student United Kingdom',
    country: 'Birleşik Krallık',
    venue: 'Silverstone',
    worldRanking: true,
    dateLabel: 'Temmuz 2027; kesin günler bekleniyor',
    dateConfirmed: false,
    sourceUrl: 'https://www.imeche.org/events/formula-student',
  },
  {
    name: 'Formula Future',
    country: 'Almanya',
    venue: 'Meppen',
    worldRanking: false,
    dateLabel: '2027 tarihi bekleniyor',
    dateConfirmed: false,
    sourceUrl: 'https://www.formula-future.eu/',
  },
  {
    name: 'Formula Student IHU',
    country: 'Yunanistan',
    venue: 'Serres',
    worldRanking: false,
    dateLabel: '2027 tarihi bekleniyor',
    dateConfirmed: false,
    sourceUrl: 'https://formulaihu.ihu.gr/',
  },
  {
    name: 'Formula Student Balkans',
    country: 'Romanya',
    venue: 'Dej',
    worldRanking: false,
    dateLabel: '2027 tarihi bekleniyor',
    dateConfirmed: false,
    sourceUrl: 'https://www.fsbalkans.ro/',
  },
  {
    name: 'Formula Student Romania',
    country: 'Romanya',
    venue: 'Bacău',
    worldRanking: false,
    dateLabel: '2027 tarihi bekleniyor',
    dateConfirmed: false,
    sourceUrl: 'https://www.formulastudent.ro/',
  },
  {
    name: 'Formula Student Russia',
    country: 'Rusya',
    venue: 'Orekhovo',
    worldRanking: false,
    dateLabel: '2027 tarihi bekleniyor',
    dateConfirmed: false,
    sourceUrl: 'https://fstudent.ru/',
  },
  {
    name: 'Formula Student Türkiye',
    country: 'Türkiye',
    venue: 'Körfez',
    worldRanking: false,
    dateLabel: '2027 tarihi bekleniyor',
    dateConfirmed: false,
    sourceUrl: 'https://www.fsturkiye.com/',
  },
];
