import { index, integer, sqliteTable, text } from 'drizzle-orm/sqlite-core';

export const applications = sqliteTable(
  'applications',
  {
    id: text('id').primaryKey(),
    submittedAt: integer('submitted_at').notNull(),
    updatedAt: integer('updated_at').notNull(),
    status: text('status').notNull().default('new'),
    assignedDepartment: text('assigned_department'),
    reviewerNote: text('reviewer_note').notNull().default(''),
    reviewedBy: text('reviewed_by'),
    reviewedAt: integer('reviewed_at'),
    emailDeliveryStatus: text('email_delivery_status').notNull().default('pending'),
    resendEmailId: text('resend_email_id'),
    name: text('name').notNull(),
    email: text('email').notNull(),
    phone: text('phone').notNull(),
    university: text('university').notNull(),
    academicDepartment: text('academic_department').notNull(),
    classLevel: text('class_level').notNull(),
    linkedin: text('linkedin').notNull().default(''),
    portfolio: text('portfolio').notNull().default(''),
    primaryTeam: text('primary_team').notNull(),
    secondaryTeam: text('secondary_team').notNull().default(''),
    programs: text('programs').notNull(),
    weeklyHours: text('weekly_hours').notNull(),
    summerParticipation: text('summer_participation').notNull(),
    busyPeriods: text('busy_periods').notNull(),
    communityExperience: text('community_experience').notNull(),
    communityDetails: text('community_details').notNull().default(''),
    projects: text('projects').notNull(),
    motivation: text('motivation').notNull(),
    responsibilityScenario: text('responsibility_scenario').notNull(),
    motivationFactor: text('motivation_factor').notNull(),
    additionalNotes: text('additional_notes').notNull().default(''),
    language: text('language').notNull().default('tr'),
  },
  (table) => [
    index('idx_applications_status_submitted_at').on(table.status, table.submittedAt),
    index('idx_applications_primary_team_submitted_at').on(table.primaryTeam, table.submittedAt),
    index('idx_applications_email').on(table.email),
  ],
);
